### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by donbowen** [LeDataSciFi/the-fin388-project-low-expectations#2]
@Natalie-Walsh Please upload the presentation file here :)

(Or attach a link to the google slides if that's what you did)

**Comment by Natalie-Walsh** [comment]
@donbowen 
https://docs.google.com/presentation/d/1d7gFvH75HNec6pPwmyjMBpGpMK4beynCbQykazHRdT8/edit#slide=id.p

**Comment by Natalie-Walsh** [comment]
@donbowen 
https://docs.google.com/presentation/d/1d7gFvH75HNec6pPwmyjMBpGpMK4beynCbQykazHRdT8/edit?usp=sharing

**Comment by Natalie-Walsh** [comment]
[Presentation Slides.pdf](https://github.com/LeDataSciFi/the-fin388-project-low-expectations/files/6495414/Presentation.Slides.pdf)

**Comment by donbowen** [comment]
Thanks!
